# Generated by Django 5.2 on 2026-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers_customuser_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
