# Generated by Django 5.2 on 2026-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, choices=[('ap', 'Andhra Pradesh'), ('tg', 'Telangana'), ('chennai', 'Chennai')], max_length=10, null=True),
        ),
    ]
