# Generated by Django 6.0.6 on 2026-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
