from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from apps.elections.models import Election, Candidate
from .models import Vote

@login_required
def cast_vote(request, election_id):
    if request.user.role != 'voter':
        messages.error(request, "Only voters are authorized to cast votes.")
        return redirect('admin_dashboard')

    if request.method == "POST":
        candidate_id = request.POST.get('candidate')
        election = get_object_or_404(Election, id=election_id, is_active=True)
        candidate = get_object_or_404(Candidate, id=candidate_id, election=election)
        if not Vote.objects.filter(voter=request.user, election=election).exists():
            Vote.objects.create(voter=request.user, election=election, candidate=candidate)
            candidate.votes_count += 1
            candidate.save()
            messages.success(request, f"Your vote for {candidate.name} has been cast successfully! ✓")
        else:
            messages.warning(request, "You have already voted in this election.")
    return redirect('voter_dashboard')


@login_required
def download_receipt(request, election_id):
    import datetime
    from django.http import HttpResponse

    if request.user.role != 'voter':
        messages.error(request, "Only voters are authorized to download receipts.")
        return redirect('admin_dashboard')

    vote = get_object_or_404(Vote, voter=request.user, election_id=election_id)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    voter_name = vote.voter.get_full_name() or "ECI Voter"

    receipt_text = f"""==================================================
🗳️ OFFICIAL SECURE ONLINE VOTING SYSTEM RECEIPT
==================================================
Receipt Code  : SEC-VOTE-{vote.id}-{vote.voter.id}
Voter Name    : {voter_name}
Voter Mobile  : {vote.voter.phone_number}
Voter Aadhaar : {vote.voter.aadhaar_number or 'N/A'}
Region/State  : {vote.voter.state.upper() if vote.voter.state else 'N/A'}

Election      : {vote.election.title}
Voted For     : {vote.candidate.name} ({vote.candidate.party_affinity}) {vote.candidate.party_symbol}

Status        : Recorded & Secured
Timestamp     : {timestamp}
==================================================
This is a secure electronic receipt generated by 
the Secure Online Voting System as proof of voting.
==================================================="""

    response = HttpResponse(receipt_text, content_type='text/plain; charset=utf-8')
    filename = f"voting_receipt_{vote.election.state}_{election_id}.txt"
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response