# Generated by Django 5.2 on 2026-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_symbol',
            field=models.CharField(blank=True, default='🗳️', max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='state',
            field=models.CharField(choices=[('ap', 'Andhra Pradesh'), ('tg', 'Telangana')], default='ap', max_length=5),
        ),
    ]
