# Generated by Django 5.2 on 2026-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_party_symbol_election_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='state',
            field=models.CharField(choices=[('ap', 'Andhra Pradesh'), ('tg', 'Telangana'), ('chennai', 'Chennai')], default='ap', max_length=10),
        ),
    ]
