# Generated by Django 5.2 on 2026-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
