# Generated by Django 6.0.6 on 2026-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_add_photo_url_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_color',
            field=models.CharField(blank=True, default='#4f46e5', max_length=7),
        ),
    ]
